name: Ejecutar Bot (Horario COL Optimizado)
on:
  schedule:
    - cron: "25 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          # Eliminamos la caché para evitar la advertencia

      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: 'stable'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Configurar pantalla virtual
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3  # Espera para asegurar que Xvfb inicia

      - name: Ejecutar script principal
        env:
          DISPLAY: :99
          PYTHONUNBUFFERED: 1  # Para ver logs en tiempo real
        run: python3 tu_script.py

      - name: Notificar en fallo (opcional)
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            core.warning("¡La ejecución del bot falló!");
